**Задание на повторение материала
1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [3]:
import numpy as np
a = np.arange(12, 24, 1)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [5]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [6]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [8]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [22]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [23]:
np.reshape(a, (3, -1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
np.reshape(a, (4, -1))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [26]:
np.reshape(a, (2, -1))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [27]:
np.reshape(a, (-1, 4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
np.reshape(a, (-1, 6))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
нет

In [19]:
a.reshape(12, 1)
print(a)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [21]:
a.ndim

2

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив

In [16]:
b = np.random.randn(3, 4)
print(b)                     

[[ 0.13231715 -0.12269446  0.87477727  0.49277689]
 [-0.52489168 -1.57578127  1.99754731  1.55886481]
 [ 0.53229158  0.2528118  -0.40754318 -0.35175961]]


In [17]:
c = b.flatten()
print(c) 

[ 0.13231715 -0.12269446  0.87477727  0.49277689 -0.52489168 -1.57578127
  1.99754731  1.55886481  0.53229158  0.2528118  -0.40754318 -0.35175961]


In [18]:
b.size == c.size

True

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [29]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [32]:
b = np.arange(20, 0, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


нет разницы

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [37]:
a = np.zeros((2, 2))
print(a)


[[0. 0.]
 [0. 0.]]


In [38]:
b = np.ones((3, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [39]:
v = np.vstack((a, b))

In [40]:
print(v)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [41]:
v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [44]:
a = np.arange(0,12)
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [45]:
At = A.T
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [47]:
B = np.dot(A, At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [48]:
B.size

16

In [49]:
np.linalg.det(B)

0.0

Определитель матрицы В равен 0, значит обратную матрицу посчитать не сможем

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [50]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [51]:
c = np.arange(0, 16)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [55]:
C = c.reshape((4, 4))
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [56]:
D = C * 10 + B

In [57]:
print(D)

[[  5  24  43  62]
 [ 54 100 146 192]
 [103 176 249 322]
 [152 252 352 452]]


In [58]:
np.linalg.det(D)

-7.685903354004529e-25

In [59]:
np.linalg.matrix_rank(D)

2

In [60]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 1.10382344e+13  5.26315789e-02 -3.31147031e+13  2.20764688e+13]
 [-8.46264636e+13  9.38249922e+13  6.62294063e+13 -7.54279349e+13]
 [ 1.36138224e+14 -1.87649984e+14 -3.31147031e+13  8.46264636e+13]
 [-6.25499948e+13  9.38249922e+13  0.00000000e+00 -3.12749974e+13]]


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [61]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0
print(D_inv)

[[1. 1. 0. 1.]
 [0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [62]:
E = np.where(D_inv, B, C)
print(E)

[[  5  14   2  32]
 [  4  50  86   7]
 [ 23   9  10 212]
 [ 12 122  14  15]]
